; ================================
; WHAT BONUS CONTENT PACKS DO CAN DO
; ================================
; Community Mods for Snapshot allow users to add new photos to the game.
; The photos will appear when doing upkskirt photos with the normal camera lens.
; A mod is allowed to have 1-100 photos, if you want more, then create a second mod (e.g. mymod2).
; The chance of a modded photo appearing scales with the amount of total modded photos the user has: minimum 10%, maximum 50% with 50+ photos.
; Support for modded photos in other areas (e.g. Sit Peek or X-ray) may be added in the future based on player demand.

; ================================
; HOW THIS WORKS
; ================================
; A Snapshot Community Pack simply needs a uniquely named folder filled with the images and a dedicated .ini file that tells the game what to import at gamestart.
; Images can also be placed in subfolders. It is recommended to playe them in a Data folder within your bonus cotnent (e.g. Snapshot!/BonusContent/mygreatmod/Data/myphoto_1.pna)
; Setup your .ini file based on this reference. Ever line that starts with ";" will be ignored by the game. You can edit this file and save it as your modname.ini (e.g. mygreatmod.ini)
; Place that ini and the photos in their own folder within Snapshot's BonusContent folder. (e.g. Snapshot!/BonusContent/mygreatmod/mygreatmod.ini)
; Allowed image formats for photos: .png, .jpg, .jpeg, .pna, .jpa
; It is recommended to use .pna and .jpa for some basic security of the mod content. You can manually rename a .png to .pna/.jpg to .jpa
; Image names must match the entries in your ini (case-insensitive). It is recommended to use the packname with a number.

[Mod]
gameID=snapshot
; the game where your pack is for: Snapshot used "snapshot" and lewd shores uses "lewdshores"
id=Rain
; A short internal ID for your mod (Don't use spaces or special characters) Must be unique
idrange=110600-110699
; Set the id range for your photos uniquely for your mod (check in discord to get your own range). Range must be within ≥100000. Max size = 100 (because one mod can’t exceed 100 photos).
title=Caught in the Rain by Sytze
; A display title for your mod used in game UI. Can have spaces etc (e.g. Cool Mod by John)
; Credits: John 
; This is a list of the people who worked on this mod. Kudos to the community!

[Defaults]
; Default settings for all photos in this pack.
; Every photo has a maximum of 4 traits: mod,position, type, color. e.g. "Community Content", "My Cool Pack", "Striped", "Blue"
; The position, type and color can be set for your pack here. See allowed positions, types and colors below.

[Special Category]
; You should add an unique name for the displayed category of your mod, in case you don't want it to be displayed as "panty"-photos. e.g. "Funny Costumes"
; You can also define an unique color for the box in which your category is displayed, this is a simple color hex code
specialCategory="Raining"
specialCategoryColor=11A8A8

[Special Traits]
;  You can add unique overwrites for types and colors in your pack. This decides: How the type/color is displayed in the game and which "real" type/color the system uses: specialType="Name displayed in the game",type used in this ini,real type used from the game (see "Allowed values" list)
; e.g. specialType="Shorts",shorts,plain -> adds the new type shorts with the name "Shorts" to the game, but it uses the stats of the type plain
; See further below for possible types and colors to reuse
specialType="Lace",lace,frill
specialType="Thong",thong,kinky
specialType="Boobs",boobs,kinky
specialType="Raincoat",raincoat,plain
specialType="Toy control",toy control,flashing
specialType="Chubby",chubby,plain
specialColor="Red",red,pink
specialColor="Yellow",yellow,pink

[Photos]
; List all photo base names (without extension). This tells the game to load them at start.
; These must match your actual file names like mymod_1.pna, mymod_2.jpa, etc.
; Separate names with commas, no spaces required (spaces are ignored).
names =rain1, rain2, rain3, rain4, rain5, rain6, rain7, rain8, rain9, rain10, rain11, rain12, rain13, rain14, rain15, rain16, rain17, rain18, rain19, rain20, rain21, rain22, rain23, rain24, rain25, rain26, rain27, rain28, rain29, rain30, rain31, rain32, rain33, rain34, rain35, rain36, rain37, rain38, rain39, rain40


; -----------------
; Optional: you can overwrite the trait values of individual photos for a better experience
; -----------------
; Format: <photoname>.<property>=<value>
; Allowed properties: position, type, color
;
; Allowed values for "position" in Snapshot:
; upskirt, jogger, xray, xJogger, bench, flasher, window
;
; Allowed values for "type":
;   plain, stripes, dots, frill, kinky, none, plug, piercing, cum, nude,
;   flashing
;
; Allowed values for "color": 
;   pink, blue, black, white, none, wet, rare
;   (Note that the color entry does not always need to be an actual color)
;
; Example: make the photo "mymod_1" a "flashing" and "wet" photo:
; mymod_1.type=flashing 
; mymod_1.color=wet
;
; Special handling for "rare": A mod is limited how many photos it can mark as "rare". Because these are special and worth much more:
;   - 1–19 photos in a mod = max 1 rare allowed
;   - 20–29 photos = max 2 rares
;   - 30–39 photos = max 3 rares
;   - and so on (+1 rare for each 10 photos), up to the maximum of 100 photos per mod
;   If you set more photos to rare than allowed, extras will be downgraded to "none".
rain1.type=plain
rain1.color=white
rain1.position=upskirt
rain2.type=lace
rain2.color=red
rain2.position=upskirt
rain3.type=lace
rain3.color=white
rain3.position=upskirt
rain4.type=thong
rain4.color=black
rain4.position=upskirt
rain5.type=thong
rain5.color=black
rain5.position=upskirt
rain6.type=lace
rain6.color=red
rain6.position=upskirt
rain7.type=boobs
rain7.color=white
rain7.position=upskirt
rain8.type=boobs
rain8.color=red
rain8.position=upskirt
rain9.type=boobs
rain9.color=red
rain9.position=upskirt
rain10.type=boobs
rain10.color=black
rain10.position=upskirt
rain11.type=boobs
rain11.color=pink
rain11.position=upskirt
rain12.type=raincoat
rain12.color=black
rain12.position=upskirt
rain13.type=boobs
rain13.color=blue
rain13.position=upskirt
rain14.type=flashing
rain14.color=white
rain14.position=upskirt
rain15.type=boobs
rain15.color=white
rain15.position=upskirt
rain16.type=raincoat
rain16.color=blue
rain16.position=bench
rain17.type=plain
rain17.color=white
rain17.position=bench
rain18.type=plain
rain18.color=white
rain18.position=bench
rain19.type=plain
rain19.color=white
rain19.position=bench
rain20.type=plain
rain20.color=white
rain20.position=bench
rain21.type=lace
rain21.color=red
rain21.position=bench
rain22.type=boobs
rain22.color=white
rain22.position=upskirt
rain23.type=lace
rain23.color=white
rain23.position=bench
rain24.type=lace
rain24.color=white
rain24.position=bench
rain25.type=plain
rain25.color=white
rain25.position=bench
rain26.type=flashing
rain26.color=none
rain26.position=flasher
rain27.type=flashing
rain27.color=none
rain27.position=flasher
rain28.type=flashing
rain28.color=none
rain28.position=flasher
rain29.type=flashing
rain29.color=none
rain29.position=flasher
rain30.type=flashing
rain30.color=none
rain30.position=flasher
rain31.type=flashing
rain31.color=none
rain31.position=flasher
rain32.type=flashing
rain32.color=none
rain32.position=flasher
rain33.type=flashing
rain33.color=white
rain33.position=flasher
rain34.type=toy control
rain34.color=black
rain34.position=remote
rain35.type=toy control
rain35.color=yellow
rain35.position=remote
rain36.type=toy control
rain36.color=none
rain36.position=remote
rain37.type=toy control
rain37.color=pink
rain37.position=remote
rain38.type=toy control
rain38.color=yellow
rain38.position=remote
rain39.type=toy control
rain39.color=white
rain39.position=remote
rain40.type=toy control
rain40.color=yellow
rain40.position=remote